import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/ui/nav";
import Footer from "@/components/ui/footer";
import Explore from "@/components/ui/explore";
import ASide from "@/components/ui/aside";
import Top from "@/components/ui/top";
import RecoidContextProvider from "./RecoidContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// import Top from "@/components/ui/top";
// import RecoidContextProvider from "./RecoidContextProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RecoidContextProvider>
        <body className={inter.className}>
          <div className="flex h-dvh w-full flex-col text-slate-300">
            <Nav />
            <div className="flex w-full flex-grow flex-row ">
              <ASide />
              <Explore />
              <div className="flex h-full w-full flex-col">
                <Top />
                <div className="flex h-full w-full flex-1">{children}</div>
              </div>
            </div>
            <Footer />
          </div>
        </body>
      </RecoidContextProvider>
    </html>
  );
}
